### PR TITLE
Upgrade to Gecko SDK 4.1.2

### PR DESCRIPTION
**Pull request by jue89**
This PR upgrades the SDK to the latest release.

The upgrade is required to bring back SiLabs' RAIL lib support to RIOT.

I've run buildtests for all EFM32-based boards that are present in RIOT on my branch [feature/pkg-gecko_sdk_41](https://github.com/jue89/RIOT/tree/feature/pkg-gecko_sdk_41)

```sh
jue@baxxter ~/P/s/RIOT (feature/pkg-gecko_sdk_41)> BOARDS="ikea-tradfri e180-zg120b-tb slstk3400a stk3200 slstk3401a slwstk6220a stk3700 slstk3402a sltb001a stk3600 slstk3400a slwstk6000b-slwrb4150a slwstk6000b-slwrb4162a" make -C examples/default buildtest
make: Entering directory '/home/jue/Projects/ssv/RIOT/examples/default'
Building for ikea-tradfri ... success.
Building for e180-zg120b-tb ... success.
Building for slstk3400a ... success.
Building for stk3200 ... success.
Building for slstk3401a ... success.
Building for slwstk6220a ... success.
Building for stk3700 ... success.
Building for slstk3402a ... success.
Building for sltb001a ... success.
Building for stk3600 ... success.
Building for slstk3400a ... success.
Building for slwstk6000b-slwrb4150a ... success.
Building for slwstk6000b-slwrb4162a ... success.
make: Leaving directory '/home/jue/Projects/ssv/RIOT/examples/default'
```

### CODE REVIEW

**Comment by basilfx** [comment]
The changes look good. Don't have a setup to test this immediately, but I trust your tests :-)

**Comment by basilfx** [comment]
Let me know if I can merge it (saw some changes appear when I typed the previous comment).

**Comment by jue89** [comment]
Hehe, I was rewording commit messages - you got me. I think its ready for the world :-)

**Comment by basilfx** [comment]
Done! And thanks!

**Pull request merged**
